apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wikimedia-recent-change
  namespace: wikimedia
  labels:
    strimzi.io/cluster: wikimedia-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    min.insync.replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wikimedia-recent-change-dlq
  namespace: wikimedia
  labels:
    strimzi.io/cluster: wikimedia-kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 1209600000
    min.insync.replicas: 2
