apiVersion: v1
kind: Secret
metadata:
  name: mongodb-keyfile-secret
  namespace: wikimedia
type: Opaque
stringData:
  keyfile: |
    wikimediaReplicaSetKeyFileContent1234567890
    abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOP
    QRSTUVWXYZabcdefghijklmnopqrstuvwxyz012345
    67890wikimediaReplicaSetKeyFileContent12345
