apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wikimedia
type: Opaque
stringData:
  mongodb-root-username: admin
  mongodb-root-password: admin
  mongodb-database: wikimedia
  mongodb-replica-set-key: wikimediaReplicaSetKey123
