kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: wikimedia-kafka
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP
      - containerPort: 30091
        hostPort: 30091
        protocol: TCP
      - containerPort: 30092
        hostPort: 30092
        protocol: TCP
      - containerPort: 30093
        hostPort: 30093
        protocol: TCP
      - containerPort: 30411
        hostPort: 30411
        protocol: TCP
      - containerPort: 31000
        hostPort: 31000
        protocol: TCP
  - role: worker
    labels:
      node-type: kafka
  - role: worker
    labels:
      node-type: mongodb
  - role: worker
    labels:
      node-type: app
